/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CPULoad {
  user: number
  nice: number
  system: number
  interrupt: number
  idle: number
  iowait: number
}
export interface FileSystem {
  /** Used file nodes in filesystem */
  files: bigint
  /** Total file nodes in filesystem */
  filesTotal: bigint
  /** Free nodes available to non-superuser */
  filesAvail: bigint
  /** Free bytes in filesystem */
  free: bigint
  /** Free bytes available to non-superuser */
  avail: bigint
  /** Total bytes in filesystem */
  total: bigint
  /** Maximum filename length */
  nameMax: bigint
  fsType: string
  fsMountedFrom: string
  fsMountedOn: string
}
export const enum _AddrType {
  Ipv4 = 0,
  IPv6 = 1
}
export interface NetworkAddrs {
  addr: string
  netmask: string
  addrType: _AddrType
}
export interface Network {
  name: string
  addrs: Array<NetworkAddrs>
}
export const enum Unit {
  B = 0,
  KB = 1,
  MB = 2,
  GB = 3,
  TB = 4,
  PB = 5,
  KIB = 6,
  MIB = 7,
  GIB = 8,
  TIB = 9,
  PIB = 10
}
export interface StatOption {
  unit: Unit
  /** Number of decimal places to be retained */
  decimal: number
}
export class Stat {
  constructor(option?: StatOption | undefined | null)
  setOption(option: StatOption): void
  mounts(): Array<FileSystem>
  mountAt(at: string): FileSystem
  blockDeviceStatistics(): void
  networks(): Array<Network>
  cpuLoadAggregate(): CPULoad
  loadAverage(): void
  socketStats(): void
  uptime(): void
  swap(): void
}
